/* Bu dosya Excel modelinden otomatik üretilmiştir. */
export const pricingData = {
  "meta": {
    "title": "İstanbul Kurye Fiyat, Bölge ve Otomatik Hesaplama Modeli",
    "brand": "Venturo Express",
    "updatedAt": "27.07.2026",
    "currency": "TRY",
    "vatIncluded": false,
    "oneWay": true,
    "districtCount": 39,
    "zoneCount": 17,
    "mainlandZoneCount": 16,
    "specialZoneCode": "B17",
    "standardCrossing": "FSM / 15 Temmuz",
    "marketPositioningPremium": 0.1,
    "roundingStep": 10,
    "includedZoneKm": 10,
    "extraKmRate": {
      "motor": 10,
      "car": 20
    },
    "longDistanceThresholdKm": 20,
    "longDistanceExtraKmFactor": 2
  },
  "zoneCodes": [
    "B01",
    "B02",
    "B03",
    "B04",
    "B05",
    "B06",
    "B07",
    "B08",
    "B09",
    "B10",
    "B11",
    "B12",
    "B13",
    "B14",
    "B15",
    "B16",
    "B17"
  ],
  "zones": [
    {
      "code": "B01",
      "name": "Avrupa Merkez",
      "side": "Avrupa",
      "hub": "Mecidiyeköy",
      "districtCount": 4,
      "districts": [
        "Beşiktaş",
        "Beyoğlu",
        "Şişli",
        "Kağıthane"
      ],
      "lon": 29,
      "lat": 41.066,
      "internalKm": 8,
      "internalMin": 22,
      "note": "Yoğun iş merkezi; kısa mesafede yüksek dur-kalk ve park riski.",
      "status": "Aktif",
      "color": "#0B5D3B"
    },
    {
      "code": "B02",
      "name": "Tarihi / İç Batı",
      "side": "Avrupa",
      "hub": "Cevizlibağ",
      "districtCount": 2,
      "districts": [
        "Fatih",
        "Zeytinburnu"
      ],
      "lon": 28.92,
      "lat": 41.018,
      "internalKm": 10,
      "internalMin": 25,
      "note": "Tarihi yarımada erişimi ve yoğun cadde dokusu birlikte ele alındı.",
      "status": "Aktif",
      "color": "#14805E"
    },
    {
      "code": "B03",
      "name": "Batı İç",
      "side": "Avrupa",
      "hub": "Otogar / Esenler",
      "districtCount": 3,
      "districts": [
        "Bayrampaşa",
        "Esenler",
        "Güngören"
      ],
      "lon": 28.894,
      "lat": 41.041,
      "internalKm": 9,
      "internalMin": 22,
      "note": "Birbirine bitişik, E-5 ve TEM bağlantılı iç batı ilçeleri.",
      "status": "Aktif",
      "color": "#11A861"
    },
    {
      "code": "B04",
      "name": "Kuzey Haliç",
      "side": "Avrupa",
      "hub": "Gaziosmanpaşa",
      "districtCount": 3,
      "districts": [
        "Eyüpsultan",
        "Gaziosmanpaşa",
        "Sultangazi"
      ],
      "lon": 28.912,
      "lat": 41.075,
      "internalKm": 13,
      "internalMin": 30,
      "note": "Haliç kuzeyi ve TEM'e açılan yoğun yerleşim koridoru.",
      "status": "Aktif",
      "color": "#4EC487"
    },
    {
      "code": "B05",
      "name": "Boğaz Kuzey",
      "side": "Avrupa",
      "hub": "Maslak",
      "districtCount": 1,
      "districts": [
        "Sarıyer"
      ],
      "lon": 29.019,
      "lat": 41.109,
      "internalKm": 15,
      "internalMin": 32,
      "note": "Maslak merkezli; kıyı ve kuzey yerleşimleri için geniş iç mesafe.",
      "status": "Aktif",
      "color": "#2F7EA8"
    },
    {
      "code": "B06",
      "name": "Orta Batı",
      "side": "Avrupa",
      "hub": "Yenibosna",
      "districtCount": 4,
      "districts": [
        "Bakırköy",
        "Bahçelievler",
        "Bağcılar",
        "Küçükçekmece"
      ],
      "lon": 28.834,
      "lat": 40.993,
      "internalKm": 14,
      "internalMin": 28,
      "note": "E-5, Basın Ekspres ve sahil bağlantılı orta batı kümesi.",
      "status": "Aktif",
      "color": "#50A7C2"
    },
    {
      "code": "B07",
      "name": "Kuzeybatı",
      "side": "Avrupa",
      "hub": "Başakşehir",
      "districtCount": 2,
      "districts": [
        "Başakşehir",
        "Arnavutköy"
      ],
      "lon": 28.806,
      "lat": 41.096,
      "internalKm": 24,
      "internalMin": 40,
      "note": "Havalimanı ve geniş yüzölçümü nedeniyle yüksek iç mesafe varsayımı.",
      "status": "Aktif",
      "color": "#6F8CCB"
    },
    {
      "code": "B08",
      "name": "Batı Metropol",
      "side": "Avrupa",
      "hub": "Haramidere",
      "districtCount": 4,
      "districts": [
        "Avcılar",
        "Esenyurt",
        "Beylikdüzü",
        "Büyükçekmece"
      ],
      "lon": 28.66,
      "lat": 41.012,
      "internalKm": 18,
      "internalMin": 35,
      "note": "E-5 boyunca birbirine eklemlenen batı yerleşimleri.",
      "status": "Aktif",
      "color": "#8776C9"
    },
    {
      "code": "B09",
      "name": "Uzak Batı",
      "side": "Avrupa",
      "hub": "Çatalca-Silivri orta koridoru",
      "districtCount": 2,
      "districts": [
        "Çatalca",
        "Silivri"
      ],
      "lon": 28.358,
      "lat": 41.095,
      "internalKm": 32,
      "internalMin": 45,
      "note": "Çok geniş hizmet alanı; ilçe içi uzak mahalleler ayrıca teyit edilmeli.",
      "status": "Aktif",
      "color": "#6C5A9E"
    },
    {
      "code": "B10",
      "name": "Anadolu Merkez",
      "side": "Anadolu",
      "hub": "Acıbadem",
      "districtCount": 2,
      "districts": [
        "Üsküdar",
        "Kadıköy"
      ],
      "lon": 29.043,
      "lat": 41.006,
      "internalKm": 9,
      "internalMin": 24,
      "note": "İki yakanın ana merkezi; köprü ve Avrasya seçeneklerine yakın.",
      "status": "Aktif",
      "color": "#C96A13"
    },
    {
      "code": "B11",
      "name": "Anadolu İç",
      "side": "Anadolu",
      "hub": "Ataşehir",
      "districtCount": 2,
      "districts": [
        "Ümraniye",
        "Ataşehir"
      ],
      "lon": 29.113,
      "lat": 40.991,
      "internalKm": 10,
      "internalMin": 24,
      "note": "Finans merkezi, TEM ve D-100 arasında yoğun iç koridor.",
      "status": "Aktif",
      "color": "#E58A2B"
    },
    {
      "code": "B12",
      "name": "Anadolu Kuzey",
      "side": "Anadolu",
      "hub": "Çekmeköy",
      "districtCount": 2,
      "districts": [
        "Beykoz",
        "Çekmeköy"
      ],
      "lon": 29.176,
      "lat": 41.033,
      "internalKm": 18,
      "internalMin": 34,
      "note": "Geniş yüzölçümü ve kuzey bağlantıları nedeniyle yüksek iç mesafe.",
      "status": "Aktif",
      "color": "#F0A43C"
    },
    {
      "code": "B13",
      "name": "Anadolu Orta",
      "side": "Anadolu",
      "hub": "Sancaktepe",
      "districtCount": 2,
      "districts": [
        "Sancaktepe",
        "Sultanbeyli"
      ],
      "lon": 29.231,
      "lat": 40.99,
      "internalKm": 14,
      "internalMin": 28,
      "note": "TEM bağlantılı, birbirine bitişik iç doğu ilçeleri.",
      "status": "Aktif",
      "color": "#D94F4F"
    },
    {
      "code": "B14",
      "name": "Anadolu Sahil",
      "side": "Anadolu",
      "hub": "Cevizli",
      "districtCount": 2,
      "districts": [
        "Maltepe",
        "Kartal"
      ],
      "lon": 29.194,
      "lat": 40.916,
      "internalKm": 14,
      "internalMin": 28,
      "note": "D-100 ve sahil yolu boyunca kesintisiz kent dokusu.",
      "status": "Aktif",
      "color": "#E76F78"
    },
    {
      "code": "B15",
      "name": "Anadolu Doğu",
      "side": "Anadolu",
      "hub": "Aydınlı / Pendik",
      "districtCount": 2,
      "districts": [
        "Pendik",
        "Tuzla"
      ],
      "lon": 29.303,
      "lat": 40.872,
      "internalKm": 18,
      "internalMin": 34,
      "note": "Sabiha Gökçen, tersaneler ve doğu sanayi koridoru.",
      "status": "Aktif",
      "color": "#B34E78"
    },
    {
      "code": "B16",
      "name": "Uzak Kuzeydoğu",
      "side": "Anadolu",
      "hub": "Şile merkez",
      "districtCount": 1,
      "districts": [
        "Şile"
      ],
      "lon": 29.613,
      "lat": 41.176,
      "internalKm": 32,
      "internalMin": 50,
      "note": "Uzak ve dağınık kırsal hizmet alanı; mahalle bazında teyit önerilir.",
      "status": "Aktif",
      "color": "#8A4E8F"
    },
    {
      "code": "B17",
      "name": "Adalar - Özel",
      "side": "Ada",
      "hub": "Vapur iskelesi + ada içi teslim",
      "districtCount": 1,
      "districts": [
        "Adalar"
      ],
      "lon": null,
      "lat": null,
      "internalKm": null,
      "internalMin": null,
      "note": "Karayolu bağlantısı yok; deniz aktarımı ve ada içi teslim ayrı tekliflenir.",
      "status": "Özel teklif",
      "color": "#64748B"
    }
  ],
  "districts": [
    {
      "name": "Adalar",
      "zoneCode": "B17",
      "zoneName": "Adalar - Özel",
      "side": "Ada",
      "hub": "Vapur iskelesi + ada içi teslim"
    },
    {
      "name": "Arnavutköy",
      "zoneCode": "B07",
      "zoneName": "Kuzeybatı",
      "side": "Avrupa",
      "hub": "Başakşehir"
    },
    {
      "name": "Ataşehir",
      "zoneCode": "B11",
      "zoneName": "Anadolu İç",
      "side": "Anadolu",
      "hub": "Ataşehir"
    },
    {
      "name": "Avcılar",
      "zoneCode": "B08",
      "zoneName": "Batı Metropol",
      "side": "Avrupa",
      "hub": "Haramidere"
    },
    {
      "name": "Bağcılar",
      "zoneCode": "B06",
      "zoneName": "Orta Batı",
      "side": "Avrupa",
      "hub": "Yenibosna"
    },
    {
      "name": "Bahçelievler",
      "zoneCode": "B06",
      "zoneName": "Orta Batı",
      "side": "Avrupa",
      "hub": "Yenibosna"
    },
    {
      "name": "Bakırköy",
      "zoneCode": "B06",
      "zoneName": "Orta Batı",
      "side": "Avrupa",
      "hub": "Yenibosna"
    },
    {
      "name": "Başakşehir",
      "zoneCode": "B07",
      "zoneName": "Kuzeybatı",
      "side": "Avrupa",
      "hub": "Başakşehir"
    },
    {
      "name": "Bayrampaşa",
      "zoneCode": "B03",
      "zoneName": "Batı İç",
      "side": "Avrupa",
      "hub": "Otogar / Esenler"
    },
    {
      "name": "Beşiktaş",
      "zoneCode": "B01",
      "zoneName": "Avrupa Merkez",
      "side": "Avrupa",
      "hub": "Mecidiyeköy"
    },
    {
      "name": "Beykoz",
      "zoneCode": "B12",
      "zoneName": "Anadolu Kuzey",
      "side": "Anadolu",
      "hub": "Çekmeköy"
    },
    {
      "name": "Beylikdüzü",
      "zoneCode": "B08",
      "zoneName": "Batı Metropol",
      "side": "Avrupa",
      "hub": "Haramidere"
    },
    {
      "name": "Beyoğlu",
      "zoneCode": "B01",
      "zoneName": "Avrupa Merkez",
      "side": "Avrupa",
      "hub": "Mecidiyeköy"
    },
    {
      "name": "Büyükçekmece",
      "zoneCode": "B08",
      "zoneName": "Batı Metropol",
      "side": "Avrupa",
      "hub": "Haramidere"
    },
    {
      "name": "Çatalca",
      "zoneCode": "B09",
      "zoneName": "Uzak Batı",
      "side": "Avrupa",
      "hub": "Çatalca-Silivri orta koridoru"
    },
    {
      "name": "Çekmeköy",
      "zoneCode": "B12",
      "zoneName": "Anadolu Kuzey",
      "side": "Anadolu",
      "hub": "Çekmeköy"
    },
    {
      "name": "Esenler",
      "zoneCode": "B03",
      "zoneName": "Batı İç",
      "side": "Avrupa",
      "hub": "Otogar / Esenler"
    },
    {
      "name": "Esenyurt",
      "zoneCode": "B08",
      "zoneName": "Batı Metropol",
      "side": "Avrupa",
      "hub": "Haramidere"
    },
    {
      "name": "Eyüpsultan",
      "zoneCode": "B04",
      "zoneName": "Kuzey Haliç",
      "side": "Avrupa",
      "hub": "Gaziosmanpaşa"
    },
    {
      "name": "Fatih",
      "zoneCode": "B02",
      "zoneName": "Tarihi / İç Batı",
      "side": "Avrupa",
      "hub": "Cevizlibağ"
    },
    {
      "name": "Gaziosmanpaşa",
      "zoneCode": "B04",
      "zoneName": "Kuzey Haliç",
      "side": "Avrupa",
      "hub": "Gaziosmanpaşa"
    },
    {
      "name": "Güngören",
      "zoneCode": "B03",
      "zoneName": "Batı İç",
      "side": "Avrupa",
      "hub": "Otogar / Esenler"
    },
    {
      "name": "Kadıköy",
      "zoneCode": "B10",
      "zoneName": "Anadolu Merkez",
      "side": "Anadolu",
      "hub": "Acıbadem"
    },
    {
      "name": "Kağıthane",
      "zoneCode": "B01",
      "zoneName": "Avrupa Merkez",
      "side": "Avrupa",
      "hub": "Mecidiyeköy"
    },
    {
      "name": "Kartal",
      "zoneCode": "B14",
      "zoneName": "Anadolu Sahil",
      "side": "Anadolu",
      "hub": "Cevizli"
    },
    {
      "name": "Küçükçekmece",
      "zoneCode": "B06",
      "zoneName": "Orta Batı",
      "side": "Avrupa",
      "hub": "Yenibosna"
    },
    {
      "name": "Maltepe",
      "zoneCode": "B14",
      "zoneName": "Anadolu Sahil",
      "side": "Anadolu",
      "hub": "Cevizli"
    },
    {
      "name": "Pendik",
      "zoneCode": "B15",
      "zoneName": "Anadolu Doğu",
      "side": "Anadolu",
      "hub": "Aydınlı / Pendik"
    },
    {
      "name": "Sancaktepe",
      "zoneCode": "B13",
      "zoneName": "Anadolu Orta",
      "side": "Anadolu",
      "hub": "Sancaktepe"
    },
    {
      "name": "Sarıyer",
      "zoneCode": "B05",
      "zoneName": "Boğaz Kuzey",
      "side": "Avrupa",
      "hub": "Maslak"
    },
    {
      "name": "Silivri",
      "zoneCode": "B09",
      "zoneName": "Uzak Batı",
      "side": "Avrupa",
      "hub": "Çatalca-Silivri orta koridoru"
    },
    {
      "name": "Sultanbeyli",
      "zoneCode": "B13",
      "zoneName": "Anadolu Orta",
      "side": "Anadolu",
      "hub": "Sancaktepe"
    },
    {
      "name": "Sultangazi",
      "zoneCode": "B04",
      "zoneName": "Kuzey Haliç",
      "side": "Avrupa",
      "hub": "Gaziosmanpaşa"
    },
    {
      "name": "Şile",
      "zoneCode": "B16",
      "zoneName": "Uzak Kuzeydoğu",
      "side": "Anadolu",
      "hub": "Şile merkez"
    },
    {
      "name": "Şişli",
      "zoneCode": "B01",
      "zoneName": "Avrupa Merkez",
      "side": "Avrupa",
      "hub": "Mecidiyeköy"
    },
    {
      "name": "Tuzla",
      "zoneCode": "B15",
      "zoneName": "Anadolu Doğu",
      "side": "Anadolu",
      "hub": "Aydınlı / Pendik"
    },
    {
      "name": "Ümraniye",
      "zoneCode": "B11",
      "zoneName": "Anadolu İç",
      "side": "Anadolu",
      "hub": "Ataşehir"
    },
    {
      "name": "Üsküdar",
      "zoneCode": "B10",
      "zoneName": "Anadolu Merkez",
      "side": "Anadolu",
      "hub": "Acıbadem"
    },
    {
      "name": "Zeytinburnu",
      "zoneCode": "B02",
      "zoneName": "Tarihi / İç Batı",
      "side": "Avrupa",
      "hub": "Cevizlibağ"
    }
  ],
  "priorities": [
    {
      "name": "Normal",
      "factor": 1,
      "description": "Standart rota ve normal mesai"
    },
    {
      "name": "Acil",
      "factor": 1.35,
      "description": "Öncelikli kurye ataması"
    },
    {
      "name": "Ekspres",
      "factor": 1.6,
      "description": "Doğrudan rota ve zaman önceliği"
    },
    {
      "name": "Gece",
      "factor": 2,
      "description": "Gece saatlerinde kurye hizmeti"
    },
    {
      "name": "VIP",
      "factor": 2,
      "description": "En yüksek öncelik ve özel takip"
    }
  ],
  "packages": [
    {
      "name": "1 A4 Evrak",
      "factor": 1,
      "defaultDesi": 0.3,
      "description": "Standart tarife; tek evrak"
    },
    {
      "name": "Küçük Paket",
      "factor": 1.5,
      "defaultDesi": 1,
      "description": "A4 tarifesine +%50"
    },
    {
      "name": "Paket",
      "factor": 2,
      "defaultDesi": 3,
      "description": "A4 tarifesinin 2 katı"
    },
    {
      "name": "Büyük Paket",
      "factor": 3,
      "defaultDesi": 5,
      "description": "A4 tarifesinin 3 katı"
    },
    {
      "name": "Çok Büyük Paket",
      "factor": 5,
      "defaultDesi": 10,
      "description": "A4 tarifesinin 5 katı"
    }
  ],
  "desiRules": [
    {
      "vehicle": "Motor Kurye",
      "minDesi": 0,
      "factor": 1,
      "note": "0-1 desi"
    },
    {
      "vehicle": "Motor Kurye",
      "minDesi": 1.01,
      "factor": 1.15,
      "note": "1-3 desi"
    },
    {
      "vehicle": "Motor Kurye",
      "minDesi": 3.01,
      "factor": 1.35,
      "note": "3-5 desi"
    },
    {
      "vehicle": "Motor Kurye",
      "minDesi": 5.01,
      "factor": 1.75,
      "note": "5-10 desi; araçlı kurye kontrolü"
    },
    {
      "vehicle": "Motor Kurye",
      "minDesi": 10.01,
      "factor": 2.5,
      "note": "10 desi üzeri; araçlı kurye önerilir"
    },
    {
      "vehicle": "Arabalı Kurye",
      "minDesi": 0,
      "factor": 1,
      "note": "0-3 desi"
    },
    {
      "vehicle": "Arabalı Kurye",
      "minDesi": 3.01,
      "factor": 1.15,
      "note": "3-10 desi"
    },
    {
      "vehicle": "Arabalı Kurye",
      "minDesi": 10.01,
      "factor": 1.35,
      "note": "10-20 desi"
    },
    {
      "vehicle": "Arabalı Kurye",
      "minDesi": 20.01,
      "factor": 1.75,
      "note": "20-40 desi"
    },
    {
      "vehicle": "Arabalı Kurye",
      "minDesi": 40.01,
      "factor": 2.5,
      "note": "40 desi üzeri"
    }
  ],
  "parameters": [
    {
      "name": "Baz operasyon gideri",
      "motor": 45,
      "car": 70,
      "unit": "TL / sefer",
      "note": "Çağrı, yönlendirme ve temel operasyon payı"
    },
    {
      "name": "Sürücü tam maliyeti",
      "motor": 220,
      "car": 220,
      "unit": "TL / saat",
      "note": "Başlangıç varsayımı; gerçek bordro maliyetiyle güncellenmeli"
    },
    {
      "name": "Teslim alma + bırakma",
      "motor": 15,
      "car": 20,
      "unit": "dakika",
      "note": "Adres bulma, park ve teslim işlemi"
    },
    {
      "name": "Trafik süre çarpanı",
      "motor": 1.1,
      "car": 1.35,
      "unit": "x",
      "note": "OSRM tipik süresini operasyon süresine yaklaştırır"
    },
    {
      "name": "Kıtalararası ek tampon",
      "motor": 10,
      "car": 15,
      "unit": "dakika",
      "note": "Köprü yaklaşımı ve rota belirsizliği"
    },
    {
      "name": "Yakıt litre fiyatı",
      "motor": 67.03,
      "car": 78.49625,
      "unit": "TL / litre",
      "note": "EPDK 27.07.2026 bülteni; gösterge niteliğinde"
    },
    {
      "name": "Yakıt tüketimi",
      "motor": 3.2,
      "car": 8.5,
      "unit": "litre / 100 km",
      "note": "Motor ve kompakt dizel otomobil varsayımı"
    },
    {
      "name": "Bakım + aşınma",
      "motor": 3.2,
      "car": 6.5,
      "unit": "TL / km",
      "note": "Lastik, bakım, amortisman ve küçük sarf payı"
    },
    {
      "name": "Hedef brüt marj",
      "motor": 0.16,
      "car": 0.16,
      "unit": "%",
      "note": "Operasyonel risk ve kârlılık için başlangıç varsayımı"
    },
    {
      "name": "Piyasa konumlandırma primi",
      "motor": 0.1,
      "car": 0.1,
      "unit": "%",
      "note": "Piyasa ile hizalı tabanların %10 üzerinde hedef"
    },
    {
      "name": "Aynı bölge piyasa referansı",
      "motor": 292.5,
      "car": 500,
      "unit": "TL",
      "note": "Motor: İstanbul Kurye 2026 Bölge 1; araçlı: yayımlanmış piyasa tabanı"
    },
    {
      "name": "Aynı bölge minimumu",
      "motor": 330,
      "car": 550,
      "unit": "TL",
      "note": "Piyasa referansı × (1 + prim), üst 10 TL"
    },
    {
      "name": "Aynı yaka bölgeler arası referans",
      "motor": 446,
      "car": 500,
      "unit": "TL",
      "note": "Motor: Akatlar-Beyazıt örneği; araçlı: yayımlanmış alt bant"
    },
    {
      "name": "Operasyonel bölgeler arası taban",
      "motor": 400,
      "car": 700,
      "unit": "TL",
      "note": "Araç kapasite bağlama ve park/zaman alt sınırı"
    },
    {
      "name": "Aynı yaka bölgeler arası minimum",
      "motor": 500,
      "car": 700,
      "unit": "TL",
      "note": "Piyasa +%10 ile operasyonel tabanın yüksek olanı"
    },
    {
      "name": "Kıtalararası piyasa / mevcut referans",
      "motor": 520,
      "car": 900,
      "unit": "TL",
      "note": "Önceki hizalı merkezi geçiş seviyeleri"
    },
    {
      "name": "Kıtalararası minimum",
      "motor": 580,
      "car": 990,
      "unit": "TL",
      "note": "Referans × (1 + prim), üst 10 TL"
    },
    {
      "name": "FSM / 15 Temmuz geçişi",
      "motor": 25,
      "car": 59,
      "unit": "TL / tek yön",
      "note": "KGM: 6. sınıf motosiklet / 1. sınıf otomobil"
    },
    {
      "name": "Avrasya Tüneli gündüz",
      "motor": 257.4,
      "car": 330,
      "unit": "TL / tek yön",
      "note": "01.07.2026 tarifesi; standart matrise dahil değil"
    },
    {
      "name": "YSS Köprüsü",
      "motor": 75,
      "car": 110,
      "unit": "TL / tek yön",
      "note": "01.07.2026 tarifesi; KMO kesimleri hariç"
    },
    {
      "name": "Yuvarlama adımı",
      "motor": 10,
      "car": 10,
      "unit": "TL",
      "note": "Son fiyat bir üst 10 TL'ye yuvarlanır"
    },
    {
      "name": "Km dönüşüm sabiti",
      "motor": 100,
      "car": 100,
      "unit": "km",
      "note": "Litre/100 km dönüşümü"
    },
    {
      "name": "Saat dönüşüm sabiti",
      "motor": 60,
      "car": 60,
      "unit": "dakika",
      "note": "Saatlik sürücü maliyeti dönüşümü"
    },
    {
      "name": "Yakıt maliyeti / km",
      "motor": 2.14496,
      "car": 6.6721812499999995,
      "unit": "TL / km",
      "note": "Hesaplanan değer"
    },
    {
      "name": "Toplam araç değişken maliyeti",
      "motor": 5.34496,
      "car": 13.17218125,
      "unit": "TL / km",
      "note": "Yakıt + bakım/aşınma"
    },
    {
      "name": "Avrasya ham farkı",
      "motor": 232.39999999999998,
      "car": 271,
      "unit": "TL",
      "note": "Avrasya - standart köprü"
    },
    {
      "name": "Avrasya öneri tarife farkı",
      "motor": 280,
      "car": 330,
      "unit": "TL",
      "note": "Marj ve yuvarlama sonrası ek fiyat"
    },
    {
      "name": "YSS ham farkı",
      "motor": 50,
      "car": 51,
      "unit": "TL",
      "note": "YSS - standart köprü; KMO hariç"
    },
    {
      "name": "YSS öneri tarife farkı",
      "motor": 60,
      "car": 70,
      "unit": "TL",
      "note": "Marj ve yuvarlama sonrası ek fiyat; KMO hariç"
    },
    {
      "name": "Bölge tarifesine dahil mesafe",
      "motor": 10,
      "car": 10,
      "unit": "km",
      "note": "Model mesafesinin ilk 10 km'si bölge taban tarifesine dahildir"
    },
    {
      "name": "Bölge dışı ek km satış bedeli",
      "motor": 10,
      "car": 20,
      "unit": "TL / km",
      "note": "Dahil mesafeyi aşan kısım için matris fiyatına eklenir"
    },
    {
      "name": "İki kat ek km eşiği",
      "motor": 20,
      "car": 20,
      "unit": "km",
      "note": "Yalnızca bu eşiği aşan kilometre bölümü iki kat bedelle hesaplanır"
    },
    {
      "name": "20 km üzeri ek km katsayısı",
      "motor": 2,
      "car": 2,
      "unit": "x",
      "note": "Toplam fiyata değil, yalnızca 20 km üzerindeki ek kilometre bedeline uygulanır"
    }
  ],
  "distanceMatrix": [
    [
      8,
      11.9,
      13.6,
      16.9,
      7.5,
      18.2,
      24.9,
      36.4,
      75.1,
      10.3,
      16.5,
      20.1,
      27.8,
      26.5,
      43.1,
      71.9,
      "Özel"
    ],
    [
      11.9,
      10,
      4.9,
      10.8,
      18.6,
      8.8,
      18.6,
      27,
      68.8,
      13.7,
      23.5,
      31.2,
      36.4,
      30.4,
      42.9,
      83.1,
      "Özel"
    ],
    [
      13.6,
      4.9,
      9,
      8,
      19.9,
      10.3,
      14.4,
      28.3,
      64.5,
      20.6,
      34.2,
      34.9,
      42.5,
      44.2,
      62.8,
      88.7,
      "Özel"
    ],
    [
      16.9,
      10.8,
      8,
      13,
      13.4,
      21.8,
      17.8,
      31.7,
      67.9,
      24.4,
      32.4,
      33.7,
      39.7,
      42.4,
      61,
      82.1,
      "Özel"
    ],
    [
      7.5,
      18.6,
      19.9,
      13.4,
      15,
      24.9,
      23.8,
      39.8,
      76,
      14.9,
      23.8,
      25.3,
      31.3,
      31.1,
      47.7,
      73.7,
      "Özel"
    ],
    [
      18.2,
      8.8,
      10.3,
      21.8,
      24.9,
      14,
      15,
      19.3,
      65.1,
      21.8,
      31.1,
      37.6,
      45.3,
      38.5,
      51,
      89.4,
      "Özel"
    ],
    [
      24.9,
      18.6,
      14.4,
      17.8,
      23.8,
      15,
      24,
      25.1,
      61.3,
      30.9,
      41.5,
      44.1,
      50.1,
      51.5,
      70.1,
      92.6,
      "Özel"
    ],
    [
      36.4,
      27,
      28.3,
      31.7,
      39.8,
      19.3,
      25.1,
      18,
      42.5,
      40,
      53.5,
      60.1,
      66.1,
      56.7,
      69.2,
      108.6,
      "Özel"
    ],
    [
      75.1,
      68.8,
      64.5,
      67.9,
      76,
      65.1,
      61.3,
      42.5,
      32,
      82.1,
      93.7,
      96.3,
      102.3,
      103.7,
      122.4,
      141.7,
      "Özel"
    ],
    [
      10.3,
      13.7,
      20.6,
      24.4,
      14.9,
      21.8,
      30.9,
      40,
      82.1,
      9,
      8.8,
      14.7,
      22.3,
      18.2,
      30.7,
      64.7,
      "Özel"
    ],
    [
      16.5,
      23.5,
      34.2,
      32.4,
      23.8,
      31.1,
      41.5,
      53.5,
      93.7,
      8.8,
      10,
      10.4,
      15.8,
      14.8,
      27.2,
      59.7,
      "Özel"
    ],
    [
      20.1,
      31.2,
      34.9,
      33.7,
      25.3,
      37.6,
      44.1,
      60.1,
      96.3,
      14.7,
      10.4,
      18,
      9,
      19.3,
      33.9,
      53.1,
      "Özel"
    ],
    [
      27.8,
      36.4,
      42.5,
      39.7,
      31.3,
      45.3,
      50.1,
      66.1,
      102.3,
      22.3,
      15.8,
      9,
      14,
      11.1,
      23.5,
      48.6,
      "Özel"
    ],
    [
      26.5,
      30.4,
      44.2,
      42.4,
      31.1,
      38.5,
      51.5,
      56.7,
      103.7,
      18.2,
      14.8,
      19.3,
      11.1,
      14,
      13.8,
      59.6,
      "Özel"
    ],
    [
      43.1,
      42.9,
      62.8,
      61,
      47.7,
      51,
      70.1,
      69.2,
      122.4,
      30.7,
      27.2,
      33.9,
      23.5,
      13.8,
      18,
      71.5,
      "Özel"
    ],
    [
      71.9,
      83.1,
      88.7,
      82.1,
      73.7,
      89.4,
      92.6,
      108.6,
      141.7,
      64.7,
      59.7,
      53.1,
      48.6,
      59.6,
      71.5,
      32,
      "Özel"
    ],
    [
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel"
    ]
  ],
  "durationMatrix": [
    [
      22,
      14,
      17,
      20,
      9,
      19,
      24,
      34,
      54,
      12,
      16,
      18,
      23,
      25,
      36,
      53,
      "Özel"
    ],
    [
      14,
      25,
      9,
      17,
      20,
      11,
      19,
      26,
      49,
      19,
      25,
      29,
      34,
      32,
      44,
      64,
      "Özel"
    ],
    [
      17,
      9,
      22,
      13,
      19,
      15,
      15,
      29,
      45,
      26,
      29,
      30,
      35,
      38,
      49,
      62,
      "Özel"
    ],
    [
      20,
      17,
      13,
      30,
      15,
      23,
      17,
      31,
      47,
      28,
      29,
      28,
      32,
      39,
      50,
      59,
      "Özel"
    ],
    [
      9,
      20,
      19,
      15,
      32,
      25,
      20,
      35,
      51,
      17,
      21,
      21,
      26,
      30,
      41,
      52,
      "Özel"
    ],
    [
      19,
      11,
      15,
      23,
      25,
      28,
      14,
      20,
      44,
      25,
      31,
      34,
      39,
      38,
      50,
      68,
      "Özel"
    ],
    [
      24,
      19,
      15,
      17,
      20,
      14,
      40,
      24,
      40,
      32,
      34,
      33,
      37,
      43,
      54,
      64,
      "Özel"
    ],
    [
      34,
      26,
      29,
      31,
      35,
      20,
      24,
      35,
      35,
      40,
      46,
      47,
      52,
      54,
      65,
      78,
      "Özel"
    ],
    [
      54,
      49,
      45,
      47,
      51,
      44,
      40,
      35,
      45,
      62,
      64,
      63,
      68,
      73,
      85,
      92,
      "Özel"
    ],
    [
      12,
      19,
      26,
      28,
      17,
      25,
      32,
      40,
      62,
      24,
      10,
      16,
      20,
      17,
      29,
      52,
      "Özel"
    ],
    [
      16,
      25,
      29,
      29,
      21,
      31,
      34,
      46,
      64,
      10,
      24,
      11,
      15,
      15,
      27,
      47,
      "Özel"
    ],
    [
      18,
      29,
      30,
      28,
      21,
      34,
      33,
      47,
      63,
      16,
      11,
      34,
      9,
      17,
      27,
      39,
      "Özel"
    ],
    [
      23,
      34,
      35,
      32,
      26,
      39,
      37,
      52,
      68,
      20,
      15,
      9,
      28,
      11,
      22,
      39,
      "Özel"
    ],
    [
      25,
      32,
      38,
      39,
      30,
      38,
      43,
      54,
      73,
      17,
      15,
      17,
      11,
      28,
      15,
      49,
      "Özel"
    ],
    [
      36,
      44,
      49,
      50,
      41,
      50,
      54,
      65,
      85,
      29,
      27,
      27,
      22,
      15,
      34,
      56,
      "Özel"
    ],
    [
      53,
      64,
      62,
      59,
      52,
      68,
      64,
      78,
      92,
      52,
      47,
      39,
      39,
      49,
      56,
      50,
      "Özel"
    ],
    [
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel",
      "Özel"
    ]
  ],
  "motorPriceMatrix": [
    [
      330,
      500,
      500,
      500,
      500,
      500,
      500,
      520,
      860,
      580,
      580,
      580,
      580,
      580,
      640,
      910,
      "Özel teklif"
    ],
    [
      500,
      330,
      500,
      500,
      500,
      500,
      500,
      500,
      800,
      580,
      580,
      580,
      590,
      580,
      680,
      1030,
      "Özel teklif"
    ],
    [
      500,
      500,
      330,
      500,
      500,
      500,
      500,
      500,
      750,
      580,
      580,
      580,
      640,
      660,
      830,
      1060,
      "Özel teklif"
    ],
    [
      500,
      500,
      500,
      350,
      500,
      500,
      500,
      500,
      780,
      580,
      580,
      580,
      600,
      650,
      830,
      1000,
      "Özel teklif"
    ],
    [
      500,
      500,
      500,
      500,
      370,
      500,
      500,
      550,
      850,
      580,
      580,
      580,
      580,
      580,
      700,
      920,
      "Özel teklif"
    ],
    [
      500,
      500,
      500,
      500,
      500,
      350,
      500,
      500,
      750,
      580,
      580,
      600,
      670,
      620,
      760,
      1090,
      "Özel teklif"
    ],
    [
      500,
      500,
      500,
      500,
      500,
      500,
      470,
      500,
      710,
      580,
      620,
      640,
      690,
      730,
      900,
      1090,
      "Özel teklif"
    ],
    [
      520,
      500,
      500,
      500,
      550,
      500,
      500,
      410,
      560,
      640,
      760,
      810,
      870,
      820,
      950,
      1260,
      "Özel teklif"
    ],
    [
      860,
      800,
      750,
      780,
      850,
      750,
      710,
      560,
      540,
      1020,
      1100,
      1110,
      1170,
      1210,
      1380,
      1540,
      "Özel teklif"
    ],
    [
      580,
      580,
      580,
      580,
      580,
      580,
      580,
      640,
      1020,
      330,
      500,
      500,
      500,
      500,
      500,
      790,
      "Özel teklif"
    ],
    [
      580,
      580,
      580,
      580,
      580,
      580,
      620,
      760,
      1100,
      500,
      330,
      500,
      500,
      500,
      500,
      730,
      "Özel teklif"
    ],
    [
      580,
      580,
      580,
      580,
      580,
      600,
      640,
      810,
      1110,
      500,
      500,
      400,
      500,
      500,
      500,
      650,
      "Özel teklif"
    ],
    [
      580,
      590,
      640,
      600,
      580,
      670,
      690,
      870,
      1170,
      500,
      500,
      500,
      350,
      500,
      500,
      620,
      "Özel teklif"
    ],
    [
      580,
      580,
      660,
      650,
      580,
      620,
      730,
      820,
      1210,
      500,
      500,
      500,
      500,
      350,
      500,
      740,
      "Özel teklif"
    ],
    [
      640,
      680,
      830,
      830,
      700,
      760,
      900,
      950,
      1380,
      500,
      500,
      500,
      500,
      500,
      400,
      850,
      "Özel teklif"
    ],
    [
      910,
      1030,
      1060,
      1000,
      920,
      1090,
      1090,
      1260,
      1540,
      790,
      730,
      650,
      620,
      740,
      850,
      570,
      "Özel teklif"
    ],
    [
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif"
    ]
  ],
  "carPriceMatrix": [
    [
      550,
      700,
      700,
      700,
      700,
      700,
      710,
      950,
      1670,
      990,
      990,
      990,
      990,
      990,
      1200,
      1750,
      "Özel teklif"
    ],
    [
      700,
      550,
      700,
      700,
      700,
      700,
      700,
      750,
      1540,
      990,
      990,
      990,
      1080,
      990,
      1240,
      1990,
      "Özel teklif"
    ],
    [
      700,
      700,
      550,
      700,
      700,
      700,
      700,
      790,
      1450,
      990,
      1020,
      1040,
      1180,
      1230,
      1580,
      2070,
      "Özel teklif"
    ],
    [
      700,
      700,
      700,
      560,
      700,
      700,
      700,
      860,
      1520,
      990,
      990,
      1000,
      1120,
      1210,
      1560,
      1950,
      "Özel teklif"
    ],
    [
      700,
      700,
      700,
      700,
      600,
      710,
      700,
      1010,
      1670,
      990,
      990,
      990,
      990,
      990,
      1300,
      1770,
      "Özel teklif"
    ],
    [
      700,
      700,
      700,
      700,
      710,
      560,
      700,
      700,
      1460,
      990,
      990,
      1100,
      1250,
      1140,
      1410,
      2110,
      "Özel teklif"
    ],
    [
      710,
      700,
      700,
      700,
      700,
      700,
      790,
      710,
      1370,
      990,
      1160,
      1200,
      1320,
      1370,
      1730,
      2140,
      "Özel teklif"
    ],
    [
      950,
      750,
      790,
      860,
      1010,
      700,
      710,
      660,
      1050,
      1170,
      1420,
      1530,
      1650,
      1520,
      1780,
      2470,
      "Özel teklif"
    ],
    [
      1670,
      1540,
      1450,
      1520,
      1670,
      1460,
      1370,
      1050,
      940,
      1960,
      2160,
      2190,
      2320,
      2370,
      2730,
      3080,
      "Özel teklif"
    ],
    [
      990,
      990,
      990,
      990,
      990,
      990,
      990,
      1170,
      1960,
      550,
      700,
      700,
      700,
      700,
      830,
      1500,
      "Özel teklif"
    ],
    [
      990,
      990,
      1020,
      990,
      990,
      990,
      1160,
      1420,
      2160,
      700,
      550,
      700,
      700,
      700,
      760,
      1390,
      "Özel teklif"
    ],
    [
      990,
      990,
      1040,
      1000,
      990,
      1100,
      1200,
      1530,
      2190,
      700,
      700,
      660,
      700,
      700,
      870,
      1240,
      "Özel teklif"
    ],
    [
      990,
      1080,
      1180,
      1120,
      990,
      1250,
      1320,
      1650,
      2320,
      700,
      700,
      700,
      560,
      700,
      700,
      1170,
      "Özel teklif"
    ],
    [
      990,
      990,
      1230,
      1210,
      990,
      1140,
      1370,
      1520,
      2370,
      700,
      700,
      700,
      700,
      560,
      700,
      1400,
      "Özel teklif"
    ],
    [
      1200,
      1240,
      1580,
      1560,
      1300,
      1410,
      1730,
      1780,
      2730,
      830,
      760,
      870,
      700,
      700,
      660,
      1630,
      "Özel teklif"
    ],
    [
      1750,
      1990,
      2070,
      1950,
      1770,
      2110,
      2140,
      2470,
      3080,
      1500,
      1390,
      1240,
      1170,
      1400,
      1630,
      970,
      "Özel teklif"
    ],
    [
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif",
      "Özel teklif"
    ]
  ],
  "sources": [
    {
      "name": "KGM - 15 Temmuz / FSM",
      "date": "01.01.2026",
      "data": "Motosiklet 25 TL; 1. sınıf otomobil 59 TL",
      "url": "https://www.kgm.gov.tr/SiteCollectionDocuments/KGMdocuments/Otoyollar/OtoyolKopruUcret/2026Gecis_Ucret/1-15Temmuz-FSM.pdf",
      "note": "İki yönlü ücret alındığı resmi tarifede belirtilir."
    },
    {
      "name": "Avrasya Tüneli",
      "date": "01.07.2026",
      "data": "Gündüz: motosiklet 257,40 TL; otomobil 330 TL",
      "url": "https://www.avrasyatuneli.com/haberler-ve-duyurular/detay/1-temmuz-2026-itibariyla-gecerli-avrasya-tuneli-gecis-ucretleri-tarifesi",
      "note": "05:00-23:59 gündüz; standart matrise dahil edilmedi."
    },
    {
      "name": "KGM - YSS",
      "date": "01.07.2026",
      "data": "Motosiklet 75 TL; 1. sınıf otomobil 110 TL",
      "url": "https://www.kgm.gov.tr/SiteCollectionDocuments/KGMdocuments/Otoyollar/OtoyolKopruUcret/2026Gecis_Ucret/3-YSSKoprusu.pdf",
      "note": "Kuzey Çevre Otoyolu kesim ücretleri ayrıca doğar."
    },
    {
      "name": "İBB Şehir Planlama",
      "date": "27.07.2026 erişim",
      "data": "İstanbul'un 39 ilçe kapsamı",
      "url": "https://sehirplanlama.ibb.istanbul/ilceler/",
      "note": "Bölge tablosundaki ilçe toplamı bu listeye karşı kontrol edildi."
    },
    {
      "name": "EPDK bayi satış fiyatı bülteni",
      "date": "27.07.2026",
      "data": "Benzin 67,03 TL/L; motorin 78,49625 TL/L",
      "url": "https://bildirim.epdk.gov.tr/bildirim-portal/faces/pages/tarife/petrol/yonetim/petrolBultenRapor.xhtml",
      "note": "İstanbul Avrupa ortalaması; model başlangıç girdisi ve gösterge niteliğinde."
    },
    {
      "name": "OSRM Table Service / OpenStreetMap",
      "date": "27.07.2026 erişim",
      "data": "Temsil noktaları arası yol km ve tipik süre",
      "url": "https://project-osrm.org/docs/v5.24.0/api/#table-service",
      "note": "Gerçek zamanlı trafik değildir; iki yön ortalaması alınmıştır."
    },
    {
      "name": "Venturo Express örnek fiyat listesi",
      "date": "04.07.2026 PDF",
      "data": "Motorlu kurye referans minimumu ve tarife yapısı",
      "url": "/Users/bahadir.filiz/Downloads/venturo express fiyat listesi.pdf",
      "note": "Eski 9 bölgeli örnek; tüm ilçeleri kapsamadığı için yalnızca kalibrasyon referansı."
    },
    {
      "name": "İstanbul Kurye 2026 peşin tarifesi",
      "date": "2026",
      "data": "Bölge 1 içi 292,50 TL; Akatlar-Beyazıt 446 TL",
      "url": "https://istanbulkurye.com.tr/fiyat-listesi/",
      "note": "Köprü dahil, KDV hariç; motor taban fiyatlarının piyasa kıyası."
    },
    {
      "name": "34 Moto Kurye İstanbul 2026",
      "date": "Nisan 2026",
      "data": "Araçlı kurye 500-1.500 TL; paket ve öncelik fiyat bantları",
      "url": "https://www.34motokuryeistanbul.com/kurye-fiyatlari-istanbul-2026/",
      "note": "KDV dahil yayımlanmış alt bant; yönlendirici piyasa referansı."
    },
    {
      "name": "Ötüken Kurye",
      "date": "27.07.2026 erişim",
      "data": "Motorlu kurye minimum 550 TL",
      "url": "https://otukenkurye.com/",
      "note": "Köprü ve otoban hariç premium uç referansı; tek başına pazar ortalaması değildir."
    },
    {
      "name": "Türkiye İlçe Sınırları - ArcGIS",
      "date": "27.07.2026 erişim",
      "data": "İstanbul 39 ilçe sınırı GeoJSON geometrisi",
      "url": "https://services5.arcgis.com/26ObnytmBZ58Wbj8/ArcGIS/rest/services/turkiye_ilce_sinirlari/FeatureServer/0",
      "note": "Sakarya Üniversitesi Coğrafya Bölümü açıklamalı veri servisi; harita görselinde kullanıldı."
    }
  ],
  "limitations": [
    "Gerçek sürücü tam maliyeti, araç finansmanı/kirası, sigorta ve genel giderler paylaşılmadı; Parametreler sayfası güncellenmelidir.",
    "Tarifeler KDV hariç öneri satış fiyatıdır; paket ağırlığı/hacmi, bekleme, gece, Express ve VIP katsayıları kapsam dışıdır.",
    "Şile, Çatalca, Silivri, Arnavutköy ve Beykoz gibi geniş ilçelerde kesin mahalle, fiyatı anlamlı ölçüde değiştirebilir.",
    "Arabalı kurye 1. sınıf kompakt dizel otomobil varsayımıdır; panelvan/minibüs için tüketim ve geçiş sınıfı yeniden tanımlanmalıdır.",
    "Adalar karayolu tarifesine dahil değildir; vapur saati, deniz aktarımı ve ada içi teslim maliyetiyle özel tekliflenmelidir."
  ]
} as const;
